server:
  port: 8081
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springData
    username: postgres
    password: vladimir
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
