server:
  port: 8081
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springRest1
    username: postgres
    password: vladimir
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true